//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.06 at 10:14:20 PM MSK 
//


package ru.sklyarov.gar;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gar package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gar
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ADDRESSOBJECTS }
     * 
     */
    public ADDRESSOBJECTS createADDRESSOBJECTS() {
        return new ADDRESSOBJECTS();
    }

    /**
     * Create an instance of {@link ITEMS }
     * 
     */
    public ITEMS createITEMS() {
        return new ITEMS();
    }

    /**
     * Create an instance of {@link ADDRESSOBJECTTYPES }
     * 
     */
    public ADDRESSOBJECTTYPES createADDRESSOBJECTTYPES() {
        return new ADDRESSOBJECTTYPES();
    }

    /**
     * Create an instance of {@link ADDRESSOBJECTS.OBJECT }
     * 
     */
    public ADDRESSOBJECTS.OBJECT createADDRESSOBJECTSOBJECT() {
        return new ADDRESSOBJECTS.OBJECT();
    }

    /**
     * Create an instance of {@link ITEMS.ITEM }
     * 
     */
    public ITEMS.ITEM createITEMSITEM() {
        return new ITEMS.ITEM();
    }

    /**
     * Create an instance of {@link ADDRESSOBJECTTYPES.ADDRESSOBJECTTYPE }
     * 
     */
    public ADDRESSOBJECTTYPES.ADDRESSOBJECTTYPE createADDRESSOBJECTTYPESADDRESSOBJECTTYPE() {
        return new ADDRESSOBJECTTYPES.ADDRESSOBJECTTYPE();
    }

}
