//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.06 at 11:10:25 PM MSK 
//


package ru.sklyarov.gar;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.sklyarov.gar package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.sklyarov.gar
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ADDRESSOBJECTS }
     * 
     */
    public ADDRESSOBJECTS createADDRESSOBJECTS() {
        return new ADDRESSOBJECTS();
    }

    /**
     * Create an instance of {@link ITEMS }
     * 
     */
    public ITEMS createITEMS() {
        return new ITEMS();
    }

    /**
     * Create an instance of {@link ADDRESSOBJECTTYPES }
     * 
     */
    public ADDRESSOBJECTTYPES createADDRESSOBJECTTYPES() {
        return new ADDRESSOBJECTTYPES();
    }

    /**
     * Create an instance of {@link HOUSES }
     * 
     */
    public HOUSES createHOUSES() {
        return new HOUSES();
    }

    /**
     * Create an instance of {@link HOUSETYPES }
     * 
     */
    public HOUSETYPES createHOUSETYPES() {
        return new HOUSETYPES();
    }

    /**
     * Create an instance of {@link PARAMS }
     * 
     */
    public PARAMS createPARAMS() {
        return new PARAMS();
    }

    /**
     * Create an instance of {@link PARAMTYPES }
     * 
     */
    public PARAMTYPES createPARAMTYPES() {
        return new PARAMTYPES();
    }

    /**
     * Create an instance of {@link ADDRESSOBJECTS.OBJECT }
     * 
     */
    public ADDRESSOBJECTS.OBJECT createADDRESSOBJECTSOBJECT() {
        return new ADDRESSOBJECTS.OBJECT();
    }

    /**
     * Create an instance of {@link ITEMS.ITEM }
     * 
     */
    public ITEMS.ITEM createITEMSITEM() {
        return new ITEMS.ITEM();
    }

    /**
     * Create an instance of {@link ADDRESSOBJECTTYPES.ADDRESSOBJECTTYPE }
     * 
     */
    public ADDRESSOBJECTTYPES.ADDRESSOBJECTTYPE createADDRESSOBJECTTYPESADDRESSOBJECTTYPE() {
        return new ADDRESSOBJECTTYPES.ADDRESSOBJECTTYPE();
    }

    /**
     * Create an instance of {@link HOUSES.HOUSE }
     * 
     */
    public HOUSES.HOUSE createHOUSESHOUSE() {
        return new HOUSES.HOUSE();
    }

    /**
     * Create an instance of {@link HOUSETYPES.HOUSETYPE }
     * 
     */
    public HOUSETYPES.HOUSETYPE createHOUSETYPESHOUSETYPE() {
        return new HOUSETYPES.HOUSETYPE();
    }

    /**
     * Create an instance of {@link PARAMS.PARAM }
     * 
     */
    public PARAMS.PARAM createPARAMSPARAM() {
        return new PARAMS.PARAM();
    }

    /**
     * Create an instance of {@link PARAMTYPES.PARAMTYPE }
     * 
     */
    public PARAMTYPES.PARAMTYPE createPARAMTYPESPARAMTYPE() {
        return new PARAMTYPES.PARAMTYPE();
    }

}
